name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm --prefix=web/ install
    - name: Compile sources
      run: npm --prefix=web/ run-script package
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: "web/dist/"
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
