name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Compile sources
      run: npm run-script package
    - name: Lol test
      run: ls
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: "./"
      env:
        GITHUB_PAT: ${{ secrets.PAT }}
